import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/styles/globals.css";

const poppins = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex items-center justify-center h-screen w-full ${poppins.className}`}
      >
        <div className="flex flex-col h-full w-full max-w-[1100px]">
          {children}
        </div>
      </body>
    </html>
  );
}
